general {
    col.active_border = rgb(21477A) rgb(536A89) 45deg
    col.inactive_border = rgb(A8B2C0)
    gaps_in = 6
    gaps_out = 12
    border_size = 2
}

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.97
    
    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
    }
}

misc {
    background_color = rgb(CAD0D8)
}